kafka:
  topics:
    topic: fraud_topic
  server:
    bootstrap_servers: localhost:9092
  producer:
    retries: 3
    max_buffer: 10

storage:
  clickhouse:
    host: "localhost"
    port: 8123
    username: "default"
    password: ""
    jdbc_driver: "com.clickhouse.jdbc.ClickHouseDriver"
    native_driver: "com.clickhouse.spark.ClickHouseCatalog"
    database: "predictions"
    table: fraud_prediction

  delta_lake:
    minio_endpoint: "http://localhost:9000"
    minio_endpoint_sdk: "localhost:9000"
    minio_access_key: "minio"
    minio_secret_key: "minio123"
    core_bucket: "deltalake"
